version: "3.8"

services:
  nginx:
    container_name: server-nginx
    image: nginx:alpine
    restart: unless-stopped
    volumes: 
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    ports: 
      - 8080:80
    networks: 
      - laranet

  app:  
    container_name: server-laravel
    build:
      dockerfile: Dockerfile
      context: ./docker/laravel 
    image: server-laravel
    restart: unless-stopped 
    working_dir: /var/www/
    volumes:
        - ./:/var/www
    depends_on:    
      - nginx
      - db
    networks: 
      - laranet

  db:  
    container_name: server-mariadb
    image: mariadb:10.6
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      #- MARIADB_ROOT_PASSWORD=1234
      #- MARIADB_PASSWORD=1234
      #- MARIADB_USER=root
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=api
    volumes:
      - ./db_data:/var/lib/mysql
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=-03:00']
    ports:
      - 3306:3306
    networks: 
      - laranet

networks: 
  laranet:
    driver: bridge